spring:
  datasource:
    url: {$URL}
    username: {$USER}
    password: {$PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
   redis:
    host: {$REDIS_HOST}
    port: 11071
    password: {$REDIS_PASSWORD}
    timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update  # validate, update, create, create-drop-
jwt.secret: B93FAF24A680131D7683DD6516F56F20FDFDB5B519DCD2E67ED3ED4C92889F04AC0436F5DA591DD4408084E07C31CF44A03B8F2DCEFF3192895B88F972E69BA5
mail.sender: {$EMAIL_SENDER}
